version: '2.12'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'cardb'
      MYSQL_USER: 'userdev'
      MYSQL_PASSWORD: 'userdevpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: